# Data loader configuration
data:
  dataset: "movielens"
  batch_size: 2048
  normalize_data: False
  category: "1m"
  embedding_dimension: "entity" # 'user' or 'item' or 'relation' or 'entity'

# Model configuration
model:
  input_dimension: 768
  hidden_dimensions: [768, 512, 256]
  latent_dimension: 256
  codebook_clusters: 512
  num_codebook_layers: 3
  commitment_weight: 0.25

# Training configuration
train:
  learning_rate: 0.0005
  weight_decay: 0.0001
  num_epochs: 512

# Additional configuration
general:
  use_wandb: True
  wandb_project: "semantic_id_ml_1m"
  wandb_entity: "justin-hangoebl-master-thesis"
  save_model: True
